### PR TITLE
translate playground's files, took 1hour 19minutes

### PR DESCRIPTION
**Pull request by lijunhuippl**
I translated all zh-CN files in the playground. There are also some useless documents on it. Please ignore them.

### CODE REVIEW

**Comment by ConradSollitt** [comment]
Thanks, Looks great!

I'll send your sister money on PayPal for this and the JSX Loader next.

**Comment by ConradSollitt** [comment]
You can see the site live now:
https://www.dataformsjs.com/zh-CN/playground

Do you know of any good Chinese sites that I could share the site on or would you be able to help share it on some Chinese programming sites?

2 to 3 hours for that would be ok if you have time and can help, as I would like to share the site with more people but it's hard to know where to share it.

I think next for code translations we can work on FastSitePHP when you have time:

https://www.dataformsjs.com/zh-CN/

Docs (setup will be very similar to DataFormsJS):
https://github.com/fastsitephp/fastsitephp/blob/master/docs/i18n-translations.md

For FastSitePHP I did the initial translations myself using Google Translate so all work to start will be making corrections. For example I used the translation "House" rather than "Homepage".

It's mostly JSON and code files just like DataFormsJS.

**Comment by ConradSollitt** [comment]
Opps, link for FastSitePHP zh-CN site is:

https://www.fastsitephp.com/zh-CN/

**Comment by lijunhuippl** [comment]
OK! i will do it and share the site on&nbsp;Chinese programming sites i know~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conrad Sollitt"<notifications@github.com&gt;; 
发送时间: 2020年3月25日(星期三) 凌晨2:30
收件人: "dataformsjs/playground"<playground@noreply.github.com&gt;; 
抄送: "Wdihui"<951708552@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dataformsjs/playground] translate playground&#39;s files, took 1hour 19minutes (#2)





 
Opps, link for FastSitePHP zh-CN site is:
 
https://www.fastsitephp.com/zh-CN/

**Comment by ConradSollitt** [comment]
Thanks! :smile: :+1:

**Comment by ConradSollitt** [comment]
Also when translating FastSitePHP please check in work after a few hours so I can see how long it takes. I have to figure out how much I can spend right now.

**Comment by lijunhuippl** [comment]
I think I need to translate more files here than dataforms JS. I Also need to modify the original Chinese file. So, it will take about 12 to 15 hours.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conrad Sollitt"<notifications@github.com&gt;; 
发送时间: 2020年3月27日(星期五) 上午7:10
收件人: "dataformsjs/playground"<playground@noreply.github.com&gt;; 
抄送: "Wdihui"<951708552@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dataformsjs/playground] translate playground&#39;s files, took 1hour 19minutes (#2)





 
Also when translating FastSitePHP please check in work after a few hours so I can see how long it takes. I have to figure out how much I can spend right now.

**Comment by ConradSollitt** [comment]
For now please just work on [zh-CN] JSON files in the following directory:
https://github.com/fastsitephp/fastsitephp/tree/master/website/app_data/i18n

See how many can be corrected within 3 hours. And then a few (2-3) hours for time to post DataFormsJS to Chinese programming sites.

After that we'll have to stop so I can figure out what my budget is. I know that my work will likely cut my hours soon so I'll have to go on hold soon. But 6 total hours more would be great and I can pay for that.

**Comment by lijunhuippl** [comment]
ok,I will do it&nbsp; now~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conrad Sollitt"<notifications@github.com&gt;; 
发送时间: 2020年3月27日(星期五) 上午9:39
收件人: "dataformsjs/playground"<playground@noreply.github.com&gt;; 
抄送: "Wdihui"<951708552@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dataformsjs/playground] translate playground&#39;s files, took 1hour 19minutes (#2)





 
For now please just work on [zh-CN] JSON files in the following directory:
 https://github.com/fastsitephp/fastsitephp/tree/master/website/app_data/i18n
 
See how many can be corrected within 3 hours. And then a few (2-3) hours for time to post DataFormsJS to Chinese programming sites.
 
After that we'll have to stop so I can figure out what my budget is. I know that my work will likely cut my hours soon so I'll have to go on hold soon. But 6 total hours more would be great and I can pay for that.

**Comment by lijunhuippl** [comment]
I shared&nbsp;dataformsjs&nbsp;and fastsitephp on two very famous websites and one possibly famous website.https://zhuanlan.zhihu.com/p/118359532
https://blog.csdn.net/qq_31339583/article/details/105140335
https://blog.bccn.net/lijunhuipll/67061




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conrad Sollitt"<notifications@github.com&gt;; 
发送时间: 2020年3月27日(星期五) 上午9:39
收件人: "dataformsjs/playground"<playground@noreply.github.com&gt;; 
抄送: "Wdihui"<951708552@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dataformsjs/playground] translate playground&#39;s files, took 1hour 19minutes (#2)





 
For now please just work on [zh-CN] JSON files in the following directory:
 https://github.com/fastsitephp/fastsitephp/tree/master/website/app_data/i18n
 
See how many can be corrected within 3 hours. And then a few (2-3) hours for time to post DataFormsJS to Chinese programming sites.
 
After that we'll have to stop so I can figure out what my budget is. I know that my work will likely cut my hours soon so I'll have to go on hold soon. But 6 total hours more would be great and I can pay for that.

**Comment by ConradSollitt** [comment]
Thanks for all your work and help. Everything looks great!

I just sent you sister money for 5 hours on PayPal.

I think we'll have to hold off on future translations for now until I know that my income will be steady in the future.

**Comment by lijunhuippl** [comment]
ok. have a good day~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conrad Sollitt"<notifications@github.com&gt;; 
发送时间: 2020年3月28日(星期六) 上午9:59
收件人: "dataformsjs/playground"<playground@noreply.github.com&gt;; 
抄送: "Wdihui"<951708552@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dataformsjs/playground] translate playground&#39;s files, took 1hour 19minutes (#2)





 
Thanks for all your work and help. Everything looks great!
 
I just sent you sister money for 5 hours on PayPal.
 
I think we'll have to hold off on future translations for now until I know that my income will be steady in the future.

**Comment by ConradSollitt** [comment]
You too! Stay safe out there and good luck in School.

If I need additional translations I'll write your sister or reply in one of the pull requests.

**Pull request merged**
